== 2010

**_AgoraMutual - January 01, 2010. bitcointalk.org_**

So, I finally got my client to start generating and after I got my laptop optimized for the task and waited over night. My first transaction completed resulting in +50 Coins. Yay!!

However, once that transaction was complete, a new transaction hasn't started. Or maybe it has. There's only one transaction in the list but I'm up to 131 Blocks under "Status". Is this the way it's supposed to happen? Does it keep processing on the same transaction and generating coins every 120 blocks or so? Or is it supposed to start a new transaction?

I have a Screen Shot if needed. Sorry if this is a basic question but I'm sure someone will ask if I don't.

Thanks for taking the initiative on this project Mr. Satoshi. Maybe one day I can fire my bank once and for all.

**EDIT**: I decided to stop playing around and I set BitCoin up on my high powered gaming rig, forwarded 8333 to it, and started generating on it instead of my laptop. So then I transferred my previous 50 coins to that client but it's been an hour and nothing has shown up for me to accept the transfer. Both computers are on the same wireless LAN. I sent it to just the BitCoin address because I wasn't sure if I was supposed to send to my internal or external IP. I assume external because the transaction needs to be verified by other nodes. Right? I also assumed sending to the BC address only would make sure it goes through the proper channels. Did I just throw my coins away or should I wait longer? I'm new at this. Sorry.

**_sirius - January 05, 2010. bitcointalk.org_**

```
  > However, once that transaction was complete, a new transaction hasn't started. Or maybe it has. There's only one transaction in the list but I'm up to 131 Blocks under "Status". Is this the way it's supposed to happen? Does it keep processing on the same transaction and generating coins every 120 blocks or so? Or is it supposed to start a new transaction?
```

The number of blocks of a transaction is the amount of new blocks that have been generated by the whole network after the transaction. Each new block in the chain means new coins to its creator. One "generated" -transaction in your transaction list means that you have generated one block. You're not the first one to find the concept of a "block" a bit confusing on the first sight.

```
I decided to stop playing around and I set BitCoin up on my high powered gaming rig, forwarded 8333 to it, and started generating on it instead of my laptop. So then I transferred my previous 50 coins to that client but it's been an hour and nothing has shown up for me to accept the transfer.
```

There's no confirmation of incoming transactions when someone sends to your Bitcoin address, all transactions are automatically completed. Did the transaction show up in the transaction list?

```
Both computers are on the same wireless LAN. I sent it to just the BitCoin address because I wasn't sure if I was supposed to send to my internal or external IP. I assume external because the transaction needs to be verified by other nodes. Right?
```
Other nodes aren't going to know which IP you're sending to, your client just connects directly to it. Both IP's are fine as long as the connection routes to the right computer. Anyway, I'd use the inner address inside a network for simplicity.

**_Satoshi Nakamoto - January 05, 2010. bitcointalk.org_**

The transfer is immediate if you send by IP address.  If you send by bitcoin address and the recipient isn't online at the time, it might take 30 minutes or more to see it.  

Also, the recipient needs to be synced up with the block chain before it'll see the received transaction.  That means the status bar at the bottom needs to say at least 33000 blocks, like "x connections  33200 blocks  x transactions".

```
The number of blocks of a transaction is the amount of new blocks that have been generated by the whole network after the transaction. Each new block in the chain means new coins to its creator. One "generated" -transaction in your transaction list means that you have generated one block. You're not the first one to find the concept of a "block" a bit confusing on the first sight.
```

Would it be clearer if the status said "x confirmations", like:
2/unconfirmed
3/unconfirmed
4/unconfirmed
5/unconfirmed
6 confirmations
7 confirmations
8 confirmations

Each block essentially means another node has confirmed that it agrees with all transactions up to that point.

**_sirius - January 05, 2010. bitcointalk.org_**

"Confirmation" would be more informative than "block". It's good if the user can relate the number of "confirmations" to the number of "blocks" in the status bar.

---

**_RogerRabbit - January 16, 2010. bitcointalk.org_**

What exactly does the number of connections do for me? Do I generate more coins with more connections, or is it equivalent no matter what?

It seems that from time to time, Tor gets tied up and can go for a few hours with 3 or 4 connections. Then, when I restart bitcoin or restart Tor to refresh my connections, I can get 7,8, or even more (9 currently).
I haven't really been able to tell if coins generate slower or not with less connections, but I was curious if it does correlate. If not, how exactly will having more connections help me out compared to less?

**_Satoshi Nakamoto - January 20, 2010. bitcointalk.org_**

Coins generate at the same speed with any number of connections >= 1.

More connections just add redundancy.  If you only had one connection, what if that node is slow or busy, or only connected to you?  Having several connections increases the certainty that you're well connected to the network.  That hasn't been a problem in practice, the network is very thoroughly connected.  If you have 2 or 3 connections, you're fine.

---

**_The Madhatter - January 16, 2010. bitcointalk.org_**

Hello,

I have had another idea. Tongue

It would be very cool to be able to have TOR and I2P seeds. For example: I could run BT within TOR-land on a .onion address. A client could connect their BT to TOR and have it seed from a .onion address and use it as a connected peer. (Likewise for I2P: someone could run a .i2p service that is -- well -- BC).

I might setup a couple of nodes in this fashion and post the tunnels on this forum. I already run a lot of I2P and TOR nodes so adding BC to the mix is quite trivial.

I support the idea of making BC compatible with TOR and I2P to increase the privacy of the system. I mean: why re-invent the wheel? There are thousands of mix network nodes just sitting there that can be used to enhance BC. Cheesy

Cheers!

**_Satoshi Nakamoto - January 20, 2010. bitcointalk.org_**

I've been thinking about that for a while.  I want to add the backend support for .onion addresses and connecting to them, then go from there.

There aren't many .onion addresses in use for anything because the user has to go through a number of steps to create one.  Configure TOR to generate a .onion address, restart TOR, configure it with the generated address.  Perhaps this is intentional to keep TOR so it can't be integrated into file sharing programs in any sufficiently automated way.


**_riX - January 25, 2010. bitcointalk.org_**

Lately when I've been trying to send coins, the following popups twice, then the application terminates.

```
  EXCEPTION: St13runtime_error
  SendMoney() : wtxNew.AcceptTransaction() failed

  c:\Documents and Settings\username\bitcoin-0.2.0\bitcoin.exe in
  CMyApp::OnExceptionInMainLoop()
```

When i restart bitcoin.exe, the transaction is showing as 0/unconfirmed. The status do not change even when the total block count increases.

I'm running two instances of bitcoin in my home LAN, one at my desktop computer, and one in a virtual machine on my laptop, with the switch -connect=192.168.0.2 (ip of desktop computer).

This occurs when I send to my own bitcoin address, to my other computers bitcoin address and to an other bitcoin address not currently active anywhere. I'm not sending by ip.

I've been moving wallets and index-files back and forth, could this have something to do with this?

**_Satoshi Nakamoto - January 27, 2010. bitcointalk.org_**

That is what happens if you copy wallet files around.  If you copy your wallet file to a second computer, then they both think the money in the wallet is theirs.  If one spends any of it, the other doesn't know those coins are already spent and would try to spend them again, and that's the error you would hit.

Now that it's clear this is a key error message, it ought to be something more like "the money appears to be already spent...  this could happen if you used a copy of your wallet file on another computer." 

You can move or backup your wallet file, but it needs to have only one "lineage" and only used in one place at a time.  Any time you transfer money out of it, then you must no longer use any previous copies.

This brings up a good point.  In the case of restoring a backup that may be from before you spent some coins, we need to add functionality to resync it to discover which coins have already been spent.  This would not be hard to do, it just hasn't been implemented yet.  I'll add it to the list.  This would make it mostly repair the situation instead of giving that error message.

**_riX - January 27, 2010. bitcointalk.org_**

Yes, I thought it had something to do with that.

It would be nice if there was a wallet tool for merging wallet files, removing unused bitcoin addresses and as you say resyncing. (I tried to just re-download all the blocks, but as you know the transactions stayed anyway.)
What about resyncing in the future when the Merkle-tree is pruned?

**_Satoshi Nakamoto - January 28, 2010. bitcointalk.org_**

The resync idea would go through your wallet and check it against the block index to find any transactions that your current computer doesn't realize are already spent.  That could happen if they were spent on another computer with a copy of the wallet file, or you had to restore the wallet to a backup from before they were spent.  Currently, the software just assumes it always knows whether its transactions are spent because it marks them spent in wallet.dat when it spends them.

A wallet merge tool is possible to implement but much less in demand once resync solves most of the problem.  With resync, you could do about the same thing by sending all the money from one wallet to the other.  The receiver would resync and discover all its overlapping coins were spent, then receive them in the new transaction.

**_Satoshi Nakamoto - February 03, 2010._**

I uploaded this fix to the SVN.  It watches for spent coins and updates your wallet on load and also continuously as blocks come in.  I also put a better error message, but it should never hit it because it always finds spent coins ahead of time, unless you spent the same money at the same time on two computers at once.

If you want to try it, PM or e-mail me your e-mail address where I can send it as an attachment and also what OS (win, linux 32-bit, linux 64-bit).


---

In January 2010, bitcointalk user Sabunir wanted to give bitcoin a 'try'. He offered to sell a digital picture for 500 bitcoins ( roughly $1 of value ). Originially he intended to transfer the 
link of the image to the user who sent him the transaction using another transaction with 0 coins and the link in a message attached to the send. Following his message 
was a discussion around the possibility of of sending a 0 coin transaction ( not possible ) and attaching a message when sending directly to an address ( wasn't possible at the time ). 

Eventually Sabunir amended his post to just do the exhchange of links VIA PM in the forum. For brevity, I have trimmed down the conversation. 


**_Sabunir - January 24, 2010. bitcointalk.org_**

Hello all. I've decided to give Bitcoin a try. As a test, I want to see if I can make $1 USD from selling a picture. According to this, 500 Bitcoins should roughly be a dollar (after PayPal fees), right?
To get the picture, please send the coins to me and then send a Private Message stating the time you sent them. I will reply to your Private Message with a link to the picture.

Anyway, it's been a pleasure to meet you all. My Address is `1BHtsCnpmTvpgJEP7eMKEVhpJFunxSM8vq`. If this generates any interest, I could offer some more of my pictures...


**_sirius - January 25, 2010_**

Unfortunately you can't attach a message when you send to a Bitcoin address. It's possible only when sending to an IP. Sending 0 coins is also not possible.

If you want to track payments, you can give a new Bitcoin address to each customer. How to make a new address: Options -> Change your address. We could perhaps make this easier by adding next to "Send Coins" a button "Receive Coins", which would create you the new address and ask for its label.

**_RogerRabbit - January 25, 2010_**

You can't send messages to Bitcoin users unless it's the IP? That seems unnecessary. Any reasoning behind this? I think people will use Bitcoin addresses a lot more often than the IP address when sending or receiving coins.

**_sirius - January 25, 2010_**

I think it was some technical limitation. Satoshi could tell more about this?

**_Satoshi Nakamoto_**

Yes, it's a technical limitation.  Sending by bitcoin address enters the transaction into the network and the recipient discovers it from the network.  You don't connect directly with them and they don't have to be online at the time.

I very much wanted to find some way to include a short message, but the problem is, the whole world would be able to see the message.  As much as you may keep reminding people that the message is completely non-private, it would be an accident waiting to happen.

Unfortunately, ECDSA can only sign signatures, it can't encrypt messages, and we need the small size of ECDSA.  RSA can encrypt messages, but it's many times bigger than ECDSA.


**_Sabunir - January 28, 2010_**

Yes, encryption of messages would be a very good thing... So the problem is not that you can't store the message on the network, but rather, that you do not yet have a good way of encrypting it?

**_The Madhatter - January 28, 2010_**

A balance between extended transaction data while NOT becoming an instant messenger client would be nice.

**_riX - January 28, 2010_**

Why don't you make them send the email before the transaction? Then you could reply to that email with a new and unique bitcoin address. You don't even need to use email, it would be equally secure, although not that anonymous, to announce the customers email together with the bitcoin address on the frontpage of your site.

The method you are using now is equal to someone sending you cash in an envelope anonymously, including a note with the time he posted it, after which you send goods back to the first person calling you stating the time and amount in the envelope. (Including the mailman and anyone who has access to you mailbox).

Sending the email before the transaction is equal to someone calling you, getting a unique box address which to send the money to. When the money arrives to that post box, you send the goods to the customer.

**_Satoshi Nakamoto - January 29, 2010_**

The recommended ways to do a payment for an order:
  
  1) The merchant has a static IP, the customer sends to it with a comment.
  2) The merchant creates a new bitcoin address, gives it to the customer, the customer sends to that address.  This will be the standard way for website software to do it.

RSA vs ECDSA: it's not the size of the executable but the size of the data.  I thought it would be impractical if the block chain, bitcoin addresses, disk space and bandwidth requirements were all an order of magnitude bigger.  Also, even if using RSA for messages, it would still make sense to do all the bitcoin network with ECDSA and use RSA in parallel for only the message part.  In that case, everything that's been implemented up to now would be implemented exactly as it has been.

We can figure out the best way to do this much later.  It could use a separate (maybe existing) e-mail or IM infrastructure to pass messages, and instead of RSA, maybe just put a hash of the message in the transaction to prove that the transaction is for the order described in the message.  The message would have to include a salt so nobody could brute force the hash to reveal a short message.


---

**_Sabunir - January 25, 2010_**

Hello. My understanding of Bitcoin is not perfect, so I would like to ask questions about its operation. When Generating, the user will gain 50 coins after creating 120 blocks. Why does the program continue generating blocks after that point? And why does one not gain another 50 coins after generating 240 blocks?

Also, I sent a few coins to someone to test the transaction system. Even though it was just a few coins, that transaction's status currently reads "166 blocks". It seems that it will continue incrementing indefinitely. Why is this?

I thank responders for increasing my knowledge.

**_sirius - January 26, 2010_**

The user gets 50 coins when he has created 1 block. The coins can be used (they "mature") when 120 blocks have been generated by the whole network after he created the block. The number of blocks of a transaction means the number of new blocks in the whole block chain after the transaction. The whole block chain grows ad infinitum.

**_Sabunir - January 25, 2010_**

So that transaction will eventually read "1000 blocks" or more? Is this information important?

**_Satoshi Nakamoto_**

Where it says "# blocks" in the status column I'm changing it to say "# confirmations".  That might be clearer.

If you doubleclick on the transaction you get a little more information.


---

